#!/bin/sh
#
# speichern im Hautverzeichnis myWeather
##
#	ln -s /tmp/data/cam.jpg /www/addons/myHM/pic/cam/cam.jpg softlink wird nicht mehr gebraucht
    sleep 120
#
# da regascript noch nicht läuft warten wir 2 minuten. Zudem muss die
# autostartdatei mit sh autostart & aufgrufen werden. da rega erst nach den
# rc.d dateien gestartet wird
# 
# anlegen der Verzeichnisse und Dateien
#
#	mkdir /tmp/data/
#	mkdir /tmp/data/xml
#	mkdir /tmp/data/ical
#	touch /tmp/data/xml/state.xml
#	touch /tmp/data/xml/devicelist.xml
#	touch /tmp/data/xml/statelist.xml
#	touch /tmp/data/xml/sysvarlist.xml
#	touch /tmp/data/ical/basic.ics
#
# weiter
#
#    tclsh sysvarlist_ram.tcl
#sleep 1
#    tclsh statelist_ram.tcl
#sleep 1
#    tclsh devicelist_ram.tcl
# _usb seit 01.10.2017 um daten auf usb zu schreiben und zu holen _ram seit 14.10.2018 ramdisk   
    
#sleep 2
tclsh myWeather.tcl &